/**
 * 通常将表格的控制器URL定义在此处
 * 然后就可以使用/@/api/common中的baTableApi类生成各个操作的url以供table进行增删改查
 */
export const authMenu = '/index.php/admin/auth.menu/'
export const authAdmin = '/index.php/admin/auth.admin/'
export const authAdminLog = '/index.php/admin/auth.adminLog/'
export const authGroup = '/index.php/admin/auth.group/'
export const routineAttachment = '/index.php/admin/routine.attachment/'
export const userUser = '/index.php/admin/user.user/'
export const userGroup = '/index.php/admin/user.group/'
export const userRule = '/index.php/admin/user.rule/'
export const userScoreLog = '/index.php/admin/user.scoreLog/'
export const userMoneyLog = '/index.php/admin/user.moneyLog/'
export const securityDataRecycle = '/index.php/admin/security.dataRecycle/'
export const securityDataRecycleLog = '/index.php/admin/security.dataRecycleLog/'
export const securitySensitiveData = '/index.php/admin/security.sensitiveData/'
export const securitySensitiveDataLog = '/index.php/admin/security.sensitiveDataLog/'
export const testBuild = '/index.php/admin/testBuild/'
export const boothExhibition = '/index.php/admin/boothExhibition/'
export const boothActivity = '/index.php/admin/boothActivity/'
export const activity = '/index.php/admin/activity/'
export const advert = '/index.php/admin/advert/'
export const boothinfo = '/index.php/admin/boothinfo/'
export const boothtem = '/index.php/admin/boothtem/'
export const boothtype = '/index.php/admin/boothtype/'
export const ticket = '/index.php/admin/ticket/'
export const flBoothTopic = '/index.php/admin/flBoothTopic/'
export const flBoothUser = '/index.php/admin/flBoothUser/'
export const flBoothUserCollect = '/index.php/admin/flBoothUserCollect/'
export const topic = '/index.php/admin/topic/'
export const collect = '/index.php/admin/collect/'
export const exhibitor = '/index.php/admin/exhibitor/'
export const viewer = '/index.php/admin/viewer/'
export const article = '/index.php/admin/article/'
export const boothUser = '/index.php/admin/boothUser/'
export const hall = '/index.php/admin/hall/'
export const exhibition = '/index.php/admin/exhibition/'
